import { Platform, StyleSheet } from 'react-native';

import { colors } from './colors';
import { spacing } from './spacing';
import { typography } from './typography';

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.fundoApp,
  },
  app: {
    flex: 1,
  },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.fundoApp,
  },
  topBar: {
    height: 72,
    paddingHorizontal: 16,
    backgroundColor: colors.vermelhoPrincipalApp,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
  },
  brandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 10,
  },
  brandMark: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: colors.vermelhoPrincipalApp,
    color: '#fff',
    textAlign: 'center',
    lineHeight: 36,
    fontWeight: '900',
  },
  brandText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  iconButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 248, 236, 0.16)',
  },
  iconButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  menuGlyph: {
    width: 18,
    gap: 4,
  },
  menuGlyphLine: {
    height: 2,
    borderRadius: 1,
    backgroundColor: '#fff8ec',
  },
  screenBackground: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: colors.fundoApp,
  },
  content: {
    padding: spacing.lg,
    paddingBottom: 92,
  },
  welcomeContent: {
    minHeight: '100%',
    paddingBottom: 92,
  },
  authCard: {
    marginTop: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    shadowColor: '#000',
    shadowOpacity: 0.26,
    shadowRadius: 18,
    elevation: 8,
  },
  card: {
    marginBottom: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 4,
  },
  cardCentered: {
    marginBottom: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 4,
  },
  surfaceBackground: {
    overflow: 'hidden',
    backgroundColor: colors.superficieCartoesEModais,
    borderRadius: 8,
  },
  cardImageTint: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(244, 216, 172, 0.28)',
  },
  surfaceContent: {
    padding: 18,
  },
  surfaceCentered: {
    alignItems: 'stretch',
  },
  surfaceCenteredContent: {
    alignItems: 'center',
  },
  logo: {
    width: '100%',
    minHeight: 170,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  imagemLogo: {
    width: '100%',
    height: 150,
  },
  eyeImage: {
    width: 74,
    height: 74,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeImageCompact: {
    width: 62,
    height: 54,
  },
  eyeLogo: {
    width: '100%',
    height: '100%',
  },
  eyeLogoCompact: {
    width: 62,
    height: 54,
  },
  title: {
    color: colors.textoPrincipal,
    fontSize: typography.size.title,
    lineHeight: 34,
    fontWeight: '900',
    marginBottom: 6,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '900',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    marginBottom: 4,
  },
  sectionDetail: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  modalTitle: {
    flex: 1,
    color: colors.textoPrincipal,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
  },
  cardTitle: {
    flex: 1,
    color: '#1e0908',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 6,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  bookmark: {
    width: 14,
    height: 20,
    backgroundColor: colors.vermelhoPrincipalApp,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },
  subtitle: {
    color: colors.vermelhoEscuroApp,
    fontWeight: '800',
    marginBottom: 12,
  },
  bodyText: {
    color: '#4a211b',
    fontSize: typography.size.md,
    lineHeight: 20,
    marginBottom: 4,
  },
  welcomePaper: {
    minHeight: '100%',
    width: '100%',
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxxl,
    alignItems: 'center',
    overflow: 'hidden',
  },
  welcomeTint: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  welcomeTitle: {
    color: colors.vermelhoPrincipalApp,
    fontFamily: Platform.select({ ios: 'Times New Roman', android: 'serif', default: 'serif' }),
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 4,
  },
  welcomeQuote: {
    maxWidth: 310,
    color: colors.textoSecundario,
    fontSize: 13,
    lineHeight: 15,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 14,
  },
  welcomeMessage: {
    width: '100%',
    maxWidth: 320,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 9,
    backgroundColor: '#f3dfba',
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    marginBottom: 10,
  },
  welcomeMessageText: {
    color: colors.textoPrincipal,
    fontSize: 12,
    lineHeight: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  magoBoasVindas: {
    width: '112%',
    maxWidth: 430,
    height: 500,
    marginTop: 0,
  },
  aboutPaper: {
    minHeight: 760,
    marginTop: 18,
    marginBottom: 18,
    paddingHorizontal: 38,
    paddingVertical: 64,
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    backgroundColor: colors.superficieCartoesEModais,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 5,
  },
  aboutTint: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(246, 228, 196, 0.42)',
  },
  aboutPanel: {
    flex: 1,
    minHeight: 632,
    paddingTop: 0,
    paddingHorizontal: 2,
    paddingBottom: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 248, 236, 0.44)',
  },
  aboutTitle: {
    width: '100%',
    color: colors.vermelhoPrincipalApp,
    fontFamily: Platform.select({ ios: 'Times New Roman', android: 'serif', default: 'serif' }),
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 30,
  },
  aboutBody: {
    color: '#090505',
    fontFamily: Platform.select({ ios: 'Times New Roman', android: 'serif', default: 'serif' }),
    fontSize: 21,
    lineHeight: 21,
    textAlign: 'center',
    marginBottom: 30,
  },
  aboutCredits: {
    width: '100%',
    marginTop: 2,
    marginBottom: 26,
  },
  aboutCreditText: {
    color: '#090505',
    fontFamily: Platform.select({ ios: 'Times New Roman', android: 'serif', default: 'serif' }),
    fontSize: 20,
    lineHeight: 22,
  },
  aboutBackArea: {
    flexGrow: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingTop: 12,
  },
  aboutBackButton: {
    minWidth: 180,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 13,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    backgroundColor: colors.vermelhoPrincipalApp,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  aboutBackButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  aboutBackButtonPressed: {
    opacity: 0.82,
  },
  description: {
    color: colors.textoPrincipal,
    fontSize: 15,
    lineHeight: 22,
    marginVertical: 12,
  },
  muted: {
    color: '#5f2c23',
    fontSize: 14,
    fontWeight: '700',
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: '#4d4442',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  input: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(127, 21, 24, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
    color: colors.textoPrincipal,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  primary: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.vermelhoPrincipalApp,
    marginTop: 8,
    shadowColor: colors.vermelhoEscuroApp,
    shadowOpacity: 0.24,
    shadowRadius: 8,
    elevation: 3,
  },
  learnSpellButton: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.vermelhoPrincipalApp,
    marginTop: 18,
    marginBottom: 16,
    shadowColor: colors.vermelhoEscuroApp,
    shadowOpacity: 0.24,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  secondary: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(127, 21, 24, 0.18)',
    backgroundColor: 'rgba(255, 244, 225, 0.88)',
    marginTop: 8,
  },
  secondaryText: {
    color: colors.textoPrincipal,
    fontWeight: '900',
  },
  ghost: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5b8ba',
    backgroundColor: 'rgba(255, 255, 255, 0.42)',
    marginTop: 10,
  },
  ghostText: {
    color: colors.vermelhoPrincipalApp,
    fontWeight: '900',
  },
  danger: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: colors.vermelhoAcaoPerigosa,
    marginTop: 8,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 7,
    elevation: 2,
  },
  sectionHeader: {
    marginBottom: 12,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  searchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  searchInput: {
    flex: 1,
  },
  sortButton: {
    width: 62,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 198, 121, 0.64)',
    backgroundColor: 'rgba(255, 240, 211, 0.94)',
  },
  filterButton: {
    width: 48,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 198, 121, 0.64)',
    backgroundColor: 'rgba(255, 240, 211, 0.94)',
    position: 'relative',
  },
  filterGlyph: {
    width: 22,
    height: 18,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterGlyphTop: {
    width: 22,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  filterGlyphMiddle: {
    width: 14,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  filterGlyphBottom: {
    width: 7,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  filterBadge: {
    position: 'absolute',
    top: 3,
    right: 3,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    overflow: 'hidden',
    color: '#fff',
    backgroundColor: colors.fundoContadorFiltros,
    textAlign: 'center',
    lineHeight: 18,
    fontSize: 11,
    fontWeight: '900',
  },
  sortText: {
    color: colors.textoPrincipal,
    fontWeight: '900',
  },
  filterGroup: {
    marginBottom: 14,
  },
  pickerFrame: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
    backgroundColor: colors.superficieCartoesEModais,
    overflow: 'hidden',
  },
  picker: {
    minHeight: 44,
    color: colors.textoPrincipal,
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  modalActionButton: {
    flex: 1,
  },
  spellCard: {
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  tag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    color: '#fff5df',
    backgroundColor: colors.vermelhoEscuroApp,
    fontSize: 12,
    fontWeight: '800',
  },
  prepared: {
    color: colors.vermelhoEscuroApp,
    fontWeight: '900',
    marginTop: 6,
  },
  actions: {
    marginTop: 10,
  },
  folderGlyph: {
    width: 30,
    height: 22,
    justifyContent: 'flex-end',
  },
  folderTab: {
    position: 'absolute',
    top: 0,
    left: 2,
    width: 12,
    height: 7,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: '#fff',
  },
  folderBody: {
    height: 18,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  folderPlus: {
    color: colors.vermelhoPrincipalApp,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '900',
  },
  characterCard: {
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
  },
  characterPhotoPreview: {
    width: 120,
    height: 120,
    alignSelf: 'center',
    marginTop: 4,
    marginBottom: 8,
    borderRadius: 60,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(127, 21, 24, 0.18)',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
  },
  characterPhotoPreviewImage: {
    width: '100%',
    height: '100%',
  },
  characterMain: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  characterBody: {
    flex: 1,
    minWidth: 180,
  },
  inlineActions: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 2,
  },
  characterAddAction: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 34,
    minWidth: 150,
    maxWidth: 185,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#2ca32f',
  },
  characterAddActionText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
  },
  characterIconAction: {
    width: 44,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  addMagicGlyph: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMagicGlyphFrame: {
    width: 18,
    height: 14,
    borderLeftWidth: 2.5,
    borderBottomWidth: 2.5,
    borderColor: '#ffffff',
  },
  addMagicGlyphTop: {
    position: 'absolute',
    top: 0,
    left: 5,
    width: 14,
    height: 11,
    borderRadius: 2,
    backgroundColor: '#ffffff',
  },
  addMagicGlyphPlusHorizontal: {
    position: 'absolute',
    top: 4.5,
    left: 8,
    width: 8,
    height: 2.5,
    borderRadius: 2,
    backgroundColor: '#2ca32f',
  },
  addMagicGlyphPlusVertical: {
    position: 'absolute',
    top: 2,
    left: 10.75,
    width: 2.5,
    height: 8,
    borderRadius: 2,
    backgroundColor: '#2ca32f',
  },
  editGlyph: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-45deg' }],
  },
  editGlyphBody: {
    width: 22,
    height: 8,
    borderRadius: 2,
    backgroundColor: '#9c9c9c',
  },
  editGlyphTip: {
    position: 'absolute',
    right: -1,
    width: 0,
    height: 0,
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#d2d2d2',
  },
  deleteGlyph: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteGlyphLid: {
    position: 'absolute',
    top: 4,
    width: 22,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  deleteGlyphHandle: {
    position: 'absolute',
    top: 1,
    width: 10,
    height: 3,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  deleteGlyphBody: {
    position: 'absolute',
    top: 7,
    width: 19,
    height: 17,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: colors.vermelhoPrincipalApp,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteGlyphCrossA: {
    position: 'absolute',
    width: 11,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#ffffff',
    transform: [{ rotate: '45deg' }],
  },
  deleteGlyphCrossB: {
    position: 'absolute',
    width: 11,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#ffffff',
    transform: [{ rotate: '-45deg' }],
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  avatarLarge: {
    width: 92,
    height: 92,
    borderRadius: 46,
    marginBottom: 12,
  },
  avatarText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 18,
  },
  squareButton: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.vermelhoPrincipalApp,
  },
  squareButtonText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 30,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: colors.vermelhoPrincipalApp,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 8,
  },
  navButton: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  navText: {
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 12,
    fontWeight: '900',
  },
  navActive: {
    color: '#fff',
  },
  addButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.vermelhoEscuroApp,
    transform: [{ translateY: -12 }],
    borderWidth: 4,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    elevation: 6,
  },
  addButtonSpacer: {
    width: 58,
    height: 58,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 34,
  },
  navGlyphActive: {
    opacity: 1,
  },
  smallFolderGlyph: {
    width: 22,
    height: 17,
    opacity: 0.78,
    marginBottom: 2,
  },
  smallFolderTab: {
    position: 'absolute',
    top: 0,
    left: 2,
    width: 9,
    height: 5,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    backgroundColor: '#fff',
  },
  smallFolderBody: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 13,
    borderRadius: 3,
    backgroundColor: '#fff',
  },
  bookGlyph: {
    width: 24,
    height: 18,
    flexDirection: 'row',
    gap: 2,
    opacity: 0.78,
    marginBottom: 2,
  },
  bookPage: {
    flex: 1,
    borderRadius: 2,
    borderWidth: 2,
    borderColor: '#fff',
    borderTopWidth: 3,
  },
  modalLayer: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
    backgroundColor: 'rgba(47, 27, 21, 0.36)',
  },
  modal: {
    width: '100%',
    maxHeight: '88%',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.superficieCartoesEModais,
    borderWidth: 1,
    borderColor: colors.linhaDivisoria,
  },
  modalBackground: {
    maxHeight: '100%',
  },
  modalScroll: {
    maxHeight: '100%',
  },
  modalScrollContent: {
    padding: 18,
    paddingBottom: 26,
    backgroundColor: colors.superficieCartoesEModais,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  confirmDialog: {
    width: '100%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 198, 121, 0.42)',
    backgroundColor: 'rgba(255, 244, 225, 0.98)',
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 8,
  },
  confirmTitle: {
    color: colors.textoPrincipal,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    marginBottom: 10,
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(127, 21, 24, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.48)',
  },
  closeText: {
    color: colors.textoSecundario,
    fontSize: 18,
    fontWeight: '900',
  },
  pickerItem: {
    marginBottom: 10,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(127, 21, 24, 0.28)',
    backgroundColor: 'rgba(255, 248, 232, 0.96)',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  drawerLayer: {
    flex: 1,
    backgroundColor: 'rgba(47, 27, 21, 0.24)',
  },
  drawer: {
    width: 280,
    maxWidth: '82%',
    minHeight: '100%',
    padding: 18,
    paddingTop: 54,
    backgroundColor: colors.vermelhoPrincipalApp,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.18)',
  },
  drawerTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 18,
  },
  drawerItem: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  drawerItemText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  drawerDanger: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: 8,
    marginTop: 14,
    backgroundColor: colors.vermelhoEscuroApp,
  },
  toastLayer: {
    flex: 1,
    position: 'relative',
    zIndex: 100000,
    elevation: 100000,
  },
  toast: {
    position: 'absolute',
    zIndex: 100000,
    left: 16,
    right: 16,
    bottom: 74,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(142, 83, 45, 0.3)',
    backgroundColor: '#fff8ec',
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 100000,
  },
  toastSuccess: {
    borderColor: colors.sucesso,
    backgroundColor: colors.fundoSucesso,
  },
  toastError: {
    borderColor: colors.erro,
    backgroundColor: colors.fundoErro,
  },
  toastWarning: {
    borderColor: colors.aviso,
    backgroundColor: colors.fundoAviso,
  },
  toastInfo: {
    borderColor: colors.informacao,
    backgroundColor: colors.fundoInformacao,
  },
  toastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  toastIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 24,
    textAlign: 'center',
    backgroundColor: colors.informacao,
  },
  toastIconSuccess: {
    backgroundColor: colors.sucesso,
  },
  toastIconError: {
    backgroundColor: colors.erro,
  },
  toastIconWarning: {
    backgroundColor: colors.aviso,
  },
  toastIconInfo: {
    backgroundColor: colors.informacao,
  },
  toastMessage: {
    flex: 1,
  },
  toastTitle: {
    color: colors.textoPrincipal,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 2,
  },
  toastText: {
    color: colors.textoPrincipal,
    fontSize: 14,
    fontWeight: '600',
  },
  toastClose: {
    color: colors.textoSecundario,
    fontSize: 20,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
});

export default styles;
